name       : unknown-horizons
version    : 2017.2
release    : 1
source     :
    - https://github.com/unknown-horizons/unknown-horizons/releases/download/2017.2/unknown-horizons-2017.2.tar.xz : 4d2d3d1d82b9c5bbe4d49a3ee82eff70b8fec6429eb295e86cd6a381345ad7bb
license    : GPL-2.0
component  : games.strategy
summary    : Unknown Horizons is a 2D real time strategy simulation with an emphasis on economy and city building.
description: |
    Unknown Horizons is a 2D real time strategy simulation with an emphasis on economy and city building.
builddeps  :
    - fifengine
rundeps    :
    - fifengine
build      : |
    %python_setup
install    : |
    %python_install
