name       : unknown-horizons
version    : '2019.1'
release    : 7
source     :
    - git|https://github.com/unknown-horizons/unknown-horizons.git : c2f4d607b33cd3a7eb2bce46c567ce1f1d83ec59
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Unknown Horizons is a 2D real time strategy simulation with an emphasis on economy and city building.
description: |
    Unknown Horizons is a 2D real time strategy simulation with an emphasis on economy and city building.
builddeps  :
    - fifengine
    - python-distro
    - python-pillow
rundeps    :
    - fifengine
    - python-future
    - python-pillow
build      : |
    %python3_setup
    python3 horizons/engine/generate_atlases.py 2048
install    : |
    %python3_install
