name       : unknown-horizons
version    : '2019.1'
release    : 5
source     :
    - https://github.com/unknown-horizons/unknown-horizons/archive/2019.1.tar.gz : a417fd3d342212fd190e4f21be82ef13c10e1ed7c288fbbe46e46200cf3de4d8
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Unknown Horizons is a 2D real time strategy simulation with an emphasis
    on economy and city building.
description: |
    Unknown Horizons is a 2D real time strategy simulation with an emphasis on economy and city building.
builddeps  :
    - fifengine
    - python-distro
    - python-pillow
rundeps    :
    - fifengine
    - python-future
    - python-pillow
setup      : |
    %patch -p1 < $pkgfiles/replace-deprecated-distro-package.patch
build      : |
    %python3_setup
    python3 horizons/engine/generate_atlases.py 2048
install    : |
    %python3_install
